version: '3'

services:
  # https://github.com/localstack/localstack
  # API Gateway at http://localhost:4567
  # Kinesis at http://localhost:4568
  # DynamoDB at http://localhost:4569
  # DynamoDB Streams at http://localhost:4570
  # Elasticsearch at http://localhost:4571
  # S3 at http://localhost:4572
  # Firehose at http://localhost:4573
  # Lambda at http://localhost:4574
  # SNS at http://localhost:4575
  # SQS at http://localhost:4576
  # Redshift at http://localhost:4577
  # ES (Elasticsearch Service) at http://localhost:4578
  # SES at http://localhost:4579
  # Route53 at http://localhost:4580
  # CloudFormation at http://localhost:4581
  # CloudWatch at http://localhost:4582
  # SSM at http://localhost:4583
  localstack:
    image: localstack/localstack
    ports:
      - '4567-4583:4567-4583'
      - '${PORT_WEB_UI-8080}:${PORT_WEB_UI-8080}'
    environment:
      - SERVICES=${SERVICES- }
      - DEBUG=${DEBUG- }
      - DATA_DIR=${DATA_DIR- }
      - PORT_WEB_UI=${PORT_WEB_UI- }
      - LAMBDA_EXECUTOR=${LAMBDA_EXECUTOR- }
      - KINESIS_ERROR_PROBABILITY=${KINESIS_ERROR_PROBABILITY- }
      - DOCKER_HOST=unix:///var/run/docker.sock
    volumes:
      - '/private${TMPDIR:-/tmp/localstack}:/tmp/localstack'
      - '/var/run/docker.sock:/var/run/docker.sock'
  # https://hub.docker.com/_/mongo/
  # mongodb://localhost:27017
  mongo:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - /data/db

  # https://hub.docker.com/_/redis/
  # redis://127.0.0.1:6379
  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - /data

  # https://hub.docker.com/_/postgres/
  # postgres://postgres:postgres@localhost:5432/postgres
  postgres:
    image: postgres:11-alpine
    ports:
      - 5432:5432
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres

  # https://hub.docker.com/_/nats-streaming/
  # nats://localhost:4222
  # http://localhost:8222
  nats-streaming:
    image: nats-streaming:latest
    command: ['-store', 'file', '-dir', '/datastore', '-m', '8222']
    ports:
      - 4222:4222
      - 8222:8222
    volumes:
      - /datastore

  # https://www.docker.elastic.co
  # http://elastic:changeme@localhost:9200
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - /usr/share/elasticsearch/data
    environment:
      - discovery.type=single-node

  # https://hub.docker.com/r/eventstore/eventstore/
  # http://admin:changeit@localhost:1113
  # http://admin:changeit@localhost:2113
  eventstore:
    image: eventstore/eventstore:latest
    ports:
      - 2113:2113
      - 1113:1113
